# Generated by Django 3.2.9 on 2022-01-13 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubemusic', '0002_music_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='최소 한 글자 이상 입력해주세요')])),
                ('choice_mood', models.CharField(choices=[('hiphop', '힙할 때'), ('sad', '우울할 때'), ('fun', '신났을 때'), ('run', '운동할 때'), ('groove', '분위기 좋은 와인바에서'), ('study', '집중할 때')], max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='music',
            name='mood',
            field=models.CharField(choices=[('hiphop', '힙할 때'), ('sad', '우울할 때'), ('fun', '신났을 때'), ('run', '운동할 때'), ('groove', '분위기 좋은 와인바에서'), ('study', '집중할 때')], default='hiphop', max_length=6),
        ),
    ]
