# Generated by Django 3.2.9 on 2022-01-18 05:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='최소 3글자 이상 입력해주세요! '), django.core.validators.RegexValidator('[ㄱ-힣]', message='한글을 입력해주세요.')]),
        ),
    ]
